---
title: "hello.c"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The C code
This is _hello.c_:
```
    #include <R.h>

    void hello(int *n)
    {
    int i;
    
    for(i=0; i < *n; i++) {
       Rprintf("Hello, world!\n");
    }
    }
```

Compile from the terminal with:

    $ R CMD SHLIB hello.c
    
```{r warning=FALSE}
setwd(src)
dir(pattern = "hello.*")
```

    
```{r warning=FALSE}
setwd(src)

system("R CMD SHLIB hello.c")
dir(pattern = "hello.*")
```



A file _hello.so_ will be generated.

## The wrapper
We write an R function to wrap the loading and call to hello.so:
```{r warning = FALSE}
setwd(src)
if (.Platform$OS.type == "windows") dyn.load("hello.dll")
if (.Platform$OS.type == "unix")    dyn.load("hello.so")

hello <- function(n) {
  .C("hello", as.integer(n))
}

hello(7)
```


```{r}
setwd(src)
file.remove("hello.dll", "hello.o")
```

## Calling from R

From R:
```{r, warning =FALSE}
setwd(rdir)           # change folder where R scripts reside

source("hello.R")     #: load the R wrapper
hello(7)
```


